@startuml
skinparam dpi 300

[*] --> KeepingLane

KeepingLane : ON ENTRY
KeepingLane : Target lane : current lane
KeepingLane : Target vehicle Id : unknown
KeepingLane :
KeepingLane : CONTINUOUSLY
KeepingLane : Check current speed
KeepingLane : Check other vehicles
KeepingLane : Update target vehicle Id
KeepingLane --> ChangingLaneLeft : Lower lane cost,\nsafe to change lane
KeepingLane --> ChangingLaneRight : Lower lane cost,\nsafe to change lane
KeepingLane --> KeepingLane : Current lane is the best

ChangingLaneLeft : CONTINUOUSLY
ChangingLaneLeft : Check current d-coord
ChangingLaneLeft : Check current d-speed
ChangingLaneLeft --> ChangingLaneLeft : d-coord != target lane,\nd-speed > 0.3
ChangingLaneLeft --> KeepingLane : Maneuver complete

ChangingLaneRight : CONTINUOUSLY
ChangingLaneRight : Check current d-coord
ChangingLaneRight : Check current d-speed
ChangingLaneRight --> ChangingLaneRight : d-coord != target lane,\nd-speed > 0.3
ChangingLaneRight --> KeepingLane : Maneuver complete

@enduml
